module.exports = [
    {
        id: 1,
        name: 'lorem',
        image: '/path/to/img/1',
        category: 1,
        reviewId: 1,
        onSale: false,
    },
    {
        id: 2,
        name: 'ipsum',
        image: '/path/to/img/2',
        category: 2,
        reviewId: 2,
        onSale: false,
    },
    {
        id: 3,
        name: 'duo',
        image: '/path/to/img/3',
        category: 3,
        reviewId: 1,
        onSale: true,
    },
    {
        id: 4,
        name: 'ipsum duo qui',
        image: '/path/to/img/4',
        category: 4,
        reviewId: 2,
        onSale: false,
    },
    {
        id: 5,
        name: 'ipsumduoqui',
        image: '/path/to/img/5',
        category: 4,
        reviewId: 3,
        onSale: true,
    },
    {
        id: 6,
        name: 'ipsumo qui',
        image: '/path/to/img/6',
        category: 4,
        reviewId: 1,
        onSale: true,
    },
    {
        id: 7,
        name: 'ipsuo qui',
        image: '/path/to/img/7',
        category: 4,
        reviewId: 1,
        onSale: true,
    },
];
